---
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/databases/tag=uaa/name
  value: ((uaa_database_name))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/roles/name=uaa/name
  value: ((uaa_database_username))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/databases/tag=cc/name
  value: &cc_database_name "((cc_database_name))"
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/roles/name=cloud_controller/name
  value: &cc_database_username "((cc_database_username))"

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/databases/tag=cc/name
  value: *cc_database_name
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/roles/name=cloud_controller/name
  value: *cc_database_username

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/databases/tag=cc/name
  value: *cc_database_name
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/roles/name=cloud_controller/name
  value: *cc_database_username

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_schema
  value: ((bbs_database_name))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_username
  value: ((bbs_database_username))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_schema
  value: ((locket_database_name))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=locket/properties/diego/locket/sql/db_username
  value: ((locket_database_username))

- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/databases/tag=cc/name
  value: ((cc_database_name))
- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/roles/name=cloud_controller/name
  value: ((cc_database_username))

- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/databases/tag=uaa/name
  value: ((uaa_database_name))
- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/roles/name=uaa/name
  value: ((uaa_database_username))

- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/databases/tag=diego/name
  value: ((bbs_database_name))
- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/roles/name=diego/name
  value: ((bbs_database_username))

- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/databases/tag=locket/name
  value: ((locket_database_name))
- type: replace
  path: /instance_groups/name=database/jobs/name=postgres/properties/databases/roles/name=locket/name
  value: ((locket_database_username))
