vm_types:
- cloud_properties:
    instance_type: minimal-lowmem
  name: minimal-lowmem
- cloud_properties:
    instance_type: minimal
  name: minimal
- cloud_properties:
    instance_type: small-lowmem
  name: small-lowmem
- cloud_properties:
    instance_type: small
  name: small
- cloud_properties:
    instance_type: small-highmem
  name: small-highmem
- cloud_properties:
    instance_type: medium-lowmem
  name: medium-lowmem
- cloud_properties:
    instance_type: medium
  name: medium
- cloud_properties:
    instance_type: medium-highmem
  name: medium-highmem
- cloud_properties:
    instance_type: large
  name: large
- name: default
  cloud_properties:
    instance_type: small
- name: small-50GB-ephemeral-disk
  cloud_properties:
    instance_type: small-50GB-ephemeral-disk
- name: medium-highmem-100GB-ephemeral-disk
  cloud_properties:
    instance_type: medium-highmem-100GB-ephemeral-disk

disk_types:
- name: 5GB
  disk_size: 5000
- name: 10GB
  disk_size: 10000
- name: 40GB
  disk_size: 40000
- name: 100GB
  disk_size: 100000
- name: 128GB
  disk_size: 131072
- name: 512GB
  disk_size: 512000

azs:
- name: z1
  cloud_properties:
    availability_zone: ((availability_zone1))
- name: z2
  cloud_properties:
    availability_zone: ((availability_zone2))
- name: z3
  cloud_properties:
    availability_zone: ((availability_zone3))

networks:
- name: mgmt
  type: manual
  subnets:
  - azs: [z3]
    range: 10.0.0.0/20
    reserved: [10.0.0.1-10.0.0.50]
    static: [10.0.0.51-10.0.15.50]
    gateway: 10.0.0.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_mgmt))
      security_groups: [WISE-PaaS-nsg]
- name: default
  type: manual
  subnets:
  - azs: [z1]
    range: 10.0.16.0/20
    reserved: [10.0.16.1-10.0.16.50]
    static: [10.0.16.51-10.0.31.50]
    gateway: 10.0.16.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_cf1))
      security_groups: [WISE-PaaS-nsg]
  - azs: [z2]
    range: 10.0.32.0/20
    reserved: [10.0.32.1-10.0.32.50]
    static: [10.0.32.51-10.0.47.50]
    gateway: 10.0.32.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_cf2))
      security_groups: [WISE-PaaS-nsg]
  - azs: [z3]
    range: 10.0.48.0/20
    reserved: [10.0.48.1-10.0.48.50]
    static: [10.0.48.51-10.0.53.50]
    gateway: 10.0.48.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_cf3))
      security_groups: [WISE-PaaS-nsg]
- name: rabbitmq-service
  type: manual
  subnets:
  - azs: [z1,z2,z3]
    range: 10.10.0.0/16
    reserved: [10.10.0.1-10.10.0.9]
    static: [10.10.0.10-10.10.255.254]
    gateway: 10.10.0.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_rmq))
      security_groups: [WISE-PaaS-nsg]
- name: db-service
  type: manual
  subnets:
  - azs: [z1,z2,z3]
    range: 10.100.0.0/16
    reserved: [10.100.0.1-10.100.0.9]
    static: [10.100.0.10-10.100.255.254]
    gateway: 10.100.0.1
    dns: ((dns))
    cloud_properties:
      net_id: ((network_db))
      security_groups: [WISE-PaaS-nsg]
- name: vip
  type: vip
  cloud_properties:
    net_id: ((network_public))

compilation:
  workers: 3
  reuse_compilation_vms: true
  vm_type: medium-lowmem
  network: mgmt
  az: z3
