az1_zone:
az1_vswitch_range:
az1_vswitch_range_2:
az1_vswitch_range_3:
az1_vswitch_gateway:
az1_vswitch_gateway_2:
az1_vswitch_gateway_3:
az1_vswitch_id:
az1_vswitch_id_2:
az1_vswitch_id_3:

az2_zone:
az2_vswitch_range:
az2_vswitch_range_2:
az2_vswitch_range_3:
az2_vswitch_gateway:
az2_vswitch_gateway_2:
az2_vswitch_gateway_3:
az2_vswitch_id:
az2_vswitch_id_2:
az2_vswitch_id_3:

az3_zone:
az3_vswitch_range:
az3_vswitch_range_2:
az3_vswitch_range_3:
az3_vswitch_gateway:
az3_vswitch_gateway_2:
az3_vswitch_gateway_3:
az3_vswitch_id:
az3_vswitch_id_2:
az3_vswitch_id_3:


security_group_id_1:
security_group_id_2:
security_group_id_3:

http_slb_id_array: []
tcp_slb_id_array: []
diego_slb_id_array: []
rabbitmq_slb_id_array: []
