cc_database_name: ccdb
cc_database_username: ccadmin
uaa_database_name: uaadb
uaa_database_username: uaaadmin
bbs_database_name: diego
bbs_database_username: diego
locket_database_name: locket
locket_database_username: diego
